# FOSRest Configuration
fos_rest:
    body_listener: true
    routing_loader:
        default_format: json
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true